spring:
  datasource:
    #引入Druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    #配置MySQL的驱动程序类
    driver-class-name: org.gjt.mm.mysql.Driver
    #数据库连接
    url: jdbc:mysql://rm-uf67l69q8z1vz9rjuuo.mysql.rds.aliyuncs.com:3306/chat?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: chat
    password: chat123
    #数据源其他配置, DataSourceProperties中没有相关属性,默认无法绑定
    initialSize: 8
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    #配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    filters: stat,wall,logback
    maxPoolPreparedStatementPerConnectionSize: 25
    useGlobalDataSourceStat: true
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500
server:
  tomcat:
    uri-encoding: UTF-8
mybatis:  type-aliases-package: pactera.tf.chat.entity
  mapperLocations : classpath:mapper/*.xml

       